apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-kafka
  labels:
    app: twitter-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-kafka
  template:
    metadata:
      labels:
        app: twitter-kafka
    spec:
      containers:
      - name: twitter-kafka-pod
        image: localhost:5000/edna-twitter-kafka:latest