template:
    jobname: kafka-emit-test
    filename: KafkaIngestEmitJob
    jobcontext: ednaconf
    jobreplicas: 1
    jobtype: internal
    jobimage: 
      registryaddress: localhost:5000
      imagename: edna-single-kafka-test
      imagetag: latest
    jobgraph:
      import_key: "in-topic"
      export_key: "out-topic"
    jobvariables:
      import_topic: "in-topic"
      import_key: "out-topic"