template:
    jobname: edna-twitter-streamer
    filename: TwitterSampledStreamerToKafka
    jobcontext: ednaconf
    jobreplicas: 1
    jobtype: internal
    jobimage: 
      registryaddress: localhost:5000
      imagename: edna-twitter-streamer-kafka
      imagetag: latest
    jobgraph:
      import_key: "in-topic"
      export_key: "out-topic"
    jobvariables:
      import_topic: "in-topic"
      import_key: "out-topic"